#!/usr/bin/env python3
"""Redraw `docs/social-card.png`, the 1200x630 image link previews show.

`docs/` is the published surface, and everything else in it is generated by
`sentinel publish` from the registry. This one file is not: it is a raster, and
rasterising text needs a font renderer, which this project deliberately does not
carry (zero runtime dependencies, stdlib only). So the card is produced here
instead, out-of-band, and committed — and this script exists so that the
committed PNG is a reproducible artifact with a recipe rather than a binary blob
somebody once made in an image editor and nobody can re-derive.

    uv run --with pillow python tools/make_social_card.py

It is NOT part of `make verify` and never runs in CI. Pillow is not a project
dependency and must not become one; `--with` keeps it out of `uv.lock`.

**The wording is read out of `core/site.py`, not retyped here.** The card shows
the same title and the same one-sentence description the page's own `<title>`
and `<meta name="description">` carry. A card is the only surface a reader sees
before they decide whether to open the page, so a second hand-maintained copy of
that sentence would be the copy that drifts, and the drifting copy would be the
one doing the talking.

The eyebrow is the same caution the page leads with. A preview card that showed
only a name and a tagline would be the single published surface omitting it, and
this registry's whole claim is that it says what it has not checked.
"""

from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from id_churn_sentinel.core.site import (  # noqa: E402  (needs the path above)
    PAGES_URL,
    SITE_DESCRIPTION,
    SITE_TITLE,
)

OUTPUT = REPO_ROOT / "docs" / "social-card.png"

WIDTH, HEIGHT = 1200, 630
MARGIN = 84

# The site's own palette, from `_CSS` in core/site.py (light scheme).
BG = "#ffffff"
FG = "#1a1a1a"
MUTED = "#4a4a4a"
LINE = "#c9c9c9"
ACCENT = "#0b5d8a"

EYEBROW = "TECHNICAL ALPHA · MACHINE-CHECKED, NOT HUMAN-CONFIRMED"

#: Tried in order. The page asks for `system-ui`; these are the closest real
#: files on the platforms this is likely to be regenerated from.
FONT_CANDIDATES = {
    "bold": (
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/HelveticaNeue.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    ),
    "regular": (
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ),
}


def _font(weight: str, size: int) -> ImageFont.FreeTypeFont:
    for candidate in FONT_CANDIDATES[weight]:
        if Path(candidate).exists():
            return ImageFont.truetype(candidate, size)
    raise SystemExit(
        f"no {weight} font found. Tried: {', '.join(FONT_CANDIDATES[weight])}. "
        f"Add a path for this platform rather than silently falling back to a "
        f"bitmap font, which would render an unreadable card."
    )


def _wrap(
    draw: ImageDraw.ImageDraw, text: str, font: ImageFont.FreeTypeFont, limit: int
) -> list[str]:
    lines: list[str] = []
    current = ""
    for word in text.split():
        trial = f"{current} {word}".strip()
        if draw.textlength(trial, font=font) <= limit or not current:
            current = trial
        else:
            lines.append(current)
            current = word
    if current:
        lines.append(current)
    return lines


def render() -> Image.Image:
    image = Image.new("RGB", (WIDTH, HEIGHT), BG)
    draw = ImageDraw.Draw(image)
    content_width = WIDTH - 2 * MARGIN

    # A single accent rule down the left edge: the site uses borders, not fills.
    draw.rectangle([(0, 0), (10, HEIGHT)], fill=ACCENT)

    y = MARGIN
    eyebrow_font = _font("bold", 24)
    draw.text((MARGIN, y), EYEBROW, font=eyebrow_font, fill=ACCENT)
    y += 58

    draw.line([(MARGIN, y), (WIDTH - MARGIN, y)], fill=LINE, width=2)
    y += 52

    title_font = _font("bold", 82)
    draw.text((MARGIN, y), SITE_TITLE, font=title_font, fill=FG)
    y += 118

    body_font = _font("regular", 34)
    for line in _wrap(draw, SITE_DESCRIPTION, body_font, content_width):
        draw.text((MARGIN, y), line, font=body_font, fill=MUTED)
        y += 50

    footer_font = _font("regular", 26)
    footer = PAGES_URL.removeprefix("https://").rstrip("/")
    draw.text((MARGIN, HEIGHT - MARGIN - 26), footer, font=footer_font, fill=MUTED)

    return image


def main() -> int:
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    render().save(OUTPUT, format="PNG", optimize=True)
    print(f"wrote {OUTPUT.relative_to(REPO_ROOT)} ({OUTPUT.stat().st_size} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
